import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Plus, Edit, Trash, Play } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

const ClassScheduling = () => {
  const { toast } = useToast();
  const navigate = useNavigate();
  
  // Controlled form state
  const [courseName, setCourseName] = useState("");
  const [courseCode, setCourseCode] = useState("");
  const [room, setRoom] = useState("");
  const [time, setTime] = useState("");
  const [maxStudents, setMaxStudents] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [classes, setClasses] = useState([]);
  const [error, setError] = useState("");
  const [editingClass, setEditingClass] = useState<any>(null);
  const [isEditMode, setIsEditMode] = useState(false);

  // Fetch classes from DB
  const fetchClasses = async () => {
    try {
      const { data, error } = await supabase
        .from("classes")
        .select("*")
        .eq("is_active", true)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      setClasses(data || []);
    } catch (error) {
      console.error("Error fetching classes:", error);
      toast({
        title: "Error",
        description: "Failed to fetch classes",
        variant: "destructive",
      });
    }
  };

  useEffect(() => {
    fetchClasses();
  }, []);

  // Delete all attendance sessions in DB
  const handleDeleteAllSessions = async () => {
    try {
      const { error } = await supabase.from("attendance_sessions").delete().neq("id", "");
      if (error) throw error;
      
      toast({
        title: "Success",
        description: "All sessions deleted from database",
      });
      fetchClasses();
    } catch (error) {
      console.error("Error deleting sessions:", error);
      toast({
        title: "Error",
        description: "Failed to delete sessions",
        variant: "destructive",
      });
    }
  };

  // Handler for create class
  const handleCreateClass = async () => {
    setIsLoading(true);
    setError("");
    
    if (!courseName || !courseCode || !room || !time || !maxStudents) {
      setError("All fields are required.");
      setIsLoading(false);
      return;
    }

    try {
      const { data, error } = await supabase
        .from("classes")
        .insert({
          name: courseName,
          code: courseCode,
          room,
          time,
          total_students: parseInt(maxStudents),
        })
        .select("*")
        .single();

      if (error) throw error;

      toast({
        title: "Success",
        description: "Class created successfully",
      });
      
      fetchClasses();
      setCourseName("");
      setCourseCode("");
      setRoom("");
      setTime("");
      setMaxStudents("");
    } catch (error) {
      console.error("Error creating class:", error);
      setError(error.message || "Failed to create class");
      toast({
        title: "Error", 
        description: error.message || "Failed to create class",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  // Start session for a class
  const handleStartSession = async (classId) => {
    try {
      const { data, error } = await supabase
        .from("attendance_sessions")
        .insert({
          class_id: classId,
          session_code: '', // Will be auto-generated by trigger
          is_active: true,
          start_time: new Date().toISOString(),
        })
        .select("*")
        .single();
      
      if (error) throw error;

      toast({
        title: "Session Started",
        description: `Session code: ${data.session_code}`,
      });
      
      // Redirect to session page
      navigate(`/session/${data.id}`);
    } catch (error) {
      console.error("Error starting session:", error);
      toast({
        title: "Error",
        description: "Couldn't start session: " + error.message,
        variant: "destructive",
      });
    }
  };

  // Edit a class
  const handleEditClass = (classData: any) => {
    setEditingClass(classData);
    setIsEditMode(true);
    setCourseName(classData.name);
    setCourseCode(classData.code);
    setRoom(classData.room);
    setTime(classData.time);
    setMaxStudents(classData.total_students.toString());
  };

  const handleUpdateClass = async () => {
    setIsLoading(true);
    setError("");
    
    if (!courseName || !courseCode || !room || !time || !maxStudents) {
      setError("All fields are required.");
      setIsLoading(false);
      return;
    }

    try {
      const { error } = await supabase
        .from("classes")
        .update({
          name: courseName,
          code: courseCode,
          room,
          time,
          total_students: parseInt(maxStudents),
        })
        .eq("id", editingClass.id);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Class updated successfully",
      });
      
      fetchClasses();
      cancelEdit();
    } catch (error) {
      console.error("Error updating class:", error);
      setError(error.message || "Failed to update class");
      toast({
        title: "Error", 
        description: error.message || "Failed to update class",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const cancelEdit = () => {
    setIsEditMode(false);
    setEditingClass(null);
    setCourseName("");
    setCourseCode("");
    setRoom("");
    setTime("");
    setMaxStudents("");
    setError("");
  };

  // Cancel a class - notify students
  const handleCancelClass = async (classData: any) => {
    try {
      // Get enrolled students
      const { data: enrollments } = await supabase
        .from("course_enrollments")
        .select("student_id")
        .eq("class_id", classData.id);

      // Create notifications for all enrolled students
      if (enrollments && enrollments.length > 0) {
        const notifications = enrollments.map(enrollment => ({
          student_id: enrollment.student_id,
          class_id: classData.id,
          message: `Class cancelled: ${classData.name} (${classData.code}) scheduled for ${classData.time} in ${classData.room}`,
          notification_type: 'cancellation',
          created_at: new Date().toISOString(),
        }));

        await supabase.from("notifications").insert(notifications);
      }

      // Mark class as inactive
      const { error } = await supabase
        .from("classes")
        .update({ is_active: false })
        .eq("id", classData.id);

      if (error) throw error;

      toast({
        title: "Class Cancelled",
        description: `${classData.name} cancelled and students notified`,
      });
      
      fetchClasses();
    } catch (error) {
      console.error("Error cancelling class:", error);
      toast({
        title: "Error",
        description: "Failed to cancel class",
        variant: "destructive",
      });
    }
  };

  // Delete a class
  const handleDeleteClass = async (id) => {
    try {
      const { error } = await supabase.from("classes").delete().eq("id", id);
      if (error) throw error;
      
      toast({
        title: "Success",
        description: "Class deleted successfully",
      });
      fetchClasses();
    } catch (error) {
      console.error("Error deleting class:", error);
      toast({
        title: "Error",
        description: "Failed to delete class",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="min-h-screen bg-muted/30 p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-4">
            <Button variant="ghost" asChild>
              <Link to="/lecturer">
                <ArrowLeft className="h-4 w-4" />
              </Link>
            </Button>
            <div>
              <h1 className="text-3xl font-bold">Class Scheduling</h1>
              <p className="text-muted-foreground">Manage your course schedules and sessions</p>
            </div>
          </div>
          <Button variant="outline" onClick={handleDeleteAllSessions}>Delete All Sessions</Button>
        </div>

        <div className="grid gap-6 lg:grid-cols-3">
          {/* Create New Schedule Form */}
          <div className="lg:col-span-1">
            <Card className="card-elevated">
              <CardHeader>
                <CardTitle className="flex items-center">
                  {isEditMode ? <Edit className="mr-2 h-5 w-5" /> : <Plus className="mr-2 h-5 w-5" />}
                  {isEditMode ? "Edit Class" : "Create New Class"}
                </CardTitle>
                <CardDescription>
                  {isEditMode ? "Update class information" : "Set up a new class schedule"}
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="course-name">Course Name</Label>
                  <Input id="course-name" value={courseName} onChange={e => setCourseName(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="course-code">Course Code</Label>
                  <Input id="course-code" value={courseCode} onChange={e => setCourseCode(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="room">Room</Label>
                  <Input id="room" value={room} onChange={e => setRoom(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="time">Time</Label>
                  <Input id="time" value={time} onChange={e => setTime(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="max-students">Maximum Students</Label>
                  <Input id="max-students" type="number" value={maxStudents} onChange={e => setMaxStudents(e.target.value)} />
                </div>
                {error && <div className="text-red-500">{error}</div>}
                {isEditMode ? (
                  <div className="flex space-x-2">
                    <Button className="flex-1 btn-primary" onClick={handleUpdateClass} disabled={isLoading}>
                      {isLoading ? "Updating..." : "Update Class"}
                    </Button>
                    <Button variant="outline" className="flex-1" onClick={cancelEdit}>
                      Cancel
                    </Button>
                  </div>
                ) : (
                  <Button className="w-full btn-primary" onClick={handleCreateClass} disabled={isLoading}>
                    {isLoading ? "Creating..." : "Create Class"}
                  </Button>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Existing Classes */}
          <div className="lg:col-span-2">
            <Card className="card-elevated">
              <CardHeader>
                <CardTitle>Existing Classes</CardTitle>
                <CardDescription>Manage your current courses</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {classes.length === 0 && (
                    <div className="text-muted-foreground">No classes scheduled yet.</div>
                  )}
                  {classes.map((schedule) => (
                    <div key={schedule.id} className="border rounded-lg p-4 space-y-3">
                      <div className="flex items-start justify-between">
                        <div>
                          <div className="flex items-center space-x-3 mb-2">
                            <h3 className="font-semibold text-lg">{schedule.name}</h3>
                            <Badge variant="outline">{schedule.code}</Badge>
                          </div>
                          <div className="flex space-x-6 text-sm text-muted-foreground">
                            <span>{schedule.room}</span>
                            <span>{schedule.time}</span>
                            <span>{schedule.total_students} students</span>
                          </div>
                        </div>
                        <div className="flex space-x-2">
                          <Button variant="outline" size="sm" onClick={() => handleEditClass(schedule)}>
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="outline" size="sm" onClick={() => handleCancelClass(schedule)}>
                            Cancel Class
                          </Button>
                          <Button variant="outline" size="sm" onClick={() => handleDeleteClass(schedule.id)}>
                            <Trash className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                      <div className="flex justify-between items-center pt-2 border-t">
                        <div className="text-sm text-muted-foreground">
                          Next session: {schedule.time}
                        </div>
                        <Button className="btn-success" size="sm" onClick={() => handleStartSession(schedule.id)}>
                          <Play className="mr-2 h-4 w-4" />
                          Start Session
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ClassScheduling;
