// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fijovbmtczlhvmfmuuse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpam92Ym10Y3psaHZtZm11dXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTQ3OTcsImV4cCI6MjA3MDU5MDc5N30.criU_qyh8045hxIHt8eeSBcyteR4DqA2PI3s5IlBCKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});