// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzrgucyrrwwzsptnradx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cmd1Y3lycnd3enNwdG5yYWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTY1NDMsImV4cCI6MjA3MDIzMjU0M30.fiy8LmN3TvkofH9Wmq1u7ZiCtUgePhZmcGhHARvmh3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});